var chromeLocations = {
	images : 	[

					{
						"title":"blue",
						"identifier":"blue_intenso",
						"icon":"blue.png",
						"folder_loc":"intenso",
						"index_name":"index_blue.html",
					},
					{
						"title":"aqua",
						"identifier":"aqua_intenso",
						"icon":"aqua.png",
						"folder_loc":"intenso",
						"index_name":"index_aqua.html",
					},
					{
						"title":"black",
						"identifier":"black_intenso",
						"icon":"black.png",
						"folder_loc":"intenso",
						"index_name":"index_black.html",
					},
					{
						"title":"green",
						"identifier":"green_intenso",
						"icon":"green.png",
						"folder_loc":"intenso",
						"index_name":"index_green.html",
					},
					{
						"title":"grey",
						"identifier":"grey_intenso",
						"icon":"grey.png",
						"folder_loc":"intenso",
						"index_name":"index_grey.html",
					},
					{
						"title":"orange",
						"identifier":"orange_intenso",
						"icon":"orange.png",
						"folder_loc":"intenso",
						"index_name":"index_orange.html",
					},
					{
						"title":"red",
						"identifier":"red_intenso",
						"icon":"red.png",
						"folder_loc":"intenso",
						"index_name":"index_red.html",
					},
					{
						"title":"default",
						"identifier":"default",
						"icon":"default.png",
						"folder_loc":"backbase",
						"index_name":"default.html",
					}
				]
};